DemoASP/Models/Enum/Role.cs
namespace DemoASP.Models.Enum
{
   [Flags]
   public enum Role
   {
      None = 0,
      User = 1,
      Moderator = 2,
      Admin = 4,
   }
}

DemoASP/Models/ErrorViewModel.cs
namespace DemoASP.Models
{
   public class ErrorViewModel
   {
      public string? RequestId { get; set; }

      public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
   }
}

DemoASP/Models/Mappers/Mappers.cs
using DAL.Models;
using DemoASP.Models.ViewModel;

namespace DemoASP.Models.Mappers
{
   public static class Mappers
   {

      public static UserView ToUserView( this User user)
      {
         return new UserView { Id = user.Id, Role = user.Role, UserName = user.UserName };
      }
   }
}

DemoASP/Models/Mappers/UserMapper.cs
using DAL.Models;
using DemoASP.Models.ViewModel;

namespace DemoASP.Models.Mappers
{
   public static class UserMapper
   {

      public static UserView ToUserView(User user)
      {
         return new UserView { Id = user.Id, Role = user.Role, UserName = user.UserName };
      }
   }
}

DemoASP/Models/User.cs
using DemoASP.Models.Enum;

namespace DemoASP.Models
{
   public class User
   {
      public Guid Id { get; set; }
      public string UserName { get; set; }
      public string Email { get; set; }
      public string Password { get; set; }
      public Role Role { get; set; }

   }
}

DemoASP/Models/ViewModel/UserLoginForm.cs
using System.ComponentModel.DataAnnotations;

namespace DemoASP.Models.ViewModel
{
   public class UserLoginForm
   {

      [Required]
      [EmailAddress]
      public string Email { get; set; }
      [Required]
      [DataType(DataType.Password)]
      public string Password { get; set; }
   }
}

DemoASP/Models/ViewModel/UserRegisterForm.cs
using System.ComponentModel.DataAnnotations;

namespace DemoASP.Models.ViewModel
{
   public class UserRegisterForm
   {
      [Required]
      [MinLength(3, ErrorMessage = "Taille minimale : 3 Caratères")]
      public string Username { get; set; }
      [EmailAddress]
      public string Email { get; set; }
      [DataType(DataType.Password)]
      [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$")]
      public string Password { get; set; }
      [DataType(DataType.Password)]
      [Compare(nameof(Password), ErrorMessage = "Les 2 mots de passe doivent correspondre")]
      public string ConfirmPassword { get; set; }
   }
}

DemoASP/Models/ViewModel/UserView.cs
using DAL.Models.Enums;

namespace DemoASP.Models.ViewModel
{
   public class UserView
   {
      public Guid Id { get; set; }
      public string UserName { get; set; }
      public Role Role { get; set; }
   }
}

DemoASP/Controllers/GameController.cs
using DAL.Interfaces;
using DAL.Models;
using DemoASP.Tools;
using Microsoft.AspNetCore.Mvc;

namespace DemoASP.Controllers
{
   [CustomAuthorize]
   public class GameController : Controller
   {
      private readonly IGameRepository _gameRepository;
      private readonly SessionManager _session;
      public GameController(IGameRepository gameRepository, SessionManager session)
      {
         _gameRepository = gameRepository;
         _session = session;
      }
      public IActionResult Index()
      {
         return View(_gameRepository.Get<IEnumerable<Game>>());
      }
      public IActionResult Details(int id)
      {
         return View(_gameRepository.Get<Game>(route: $"{id}"));
      }
      [CustomAdmin]
      public IActionResult Create()
      {
         return View();
      }
      [HttpPost]
      public IActionResult Create(Game g)
      {
         _gameRepository.Post<Game>(new {g.Title,IdGenre = g.Genres.Id,g.Resume},route:"add", token:_session.ConnectedUser.Token);
         return RedirectToAction("Index");
      }
      [CustomAdmin]
      public IActionResult Delete(int id)
      {
         if (_gameRepository.Delete(route: $"{id}")) return RedirectToAction("Index");
         return View();
      }
      [CustomModo]
      public IActionResult Edit(int id)
      {
         return View();
      }
      [HttpPost]
      public IActionResult Edit(Game g)
      {
         //_gameRepository.Update(g);
         return View();
      }

      public IActionResult ListByGenre()
      {
         return View(_gameRepository.Get<Dictionary<string,Game>>(route:"byGenre"));
      }
      public IActionResult AddFavGame(int id)
      {
         _gameRepository.Post<object>(null,route:$"addFavori/{id}/user/{_session.ConnectedUser.Id}", token: _session.ConnectedUser.Token);
         return RedirectToAction("Index");
      }

      public IActionResult FavList(Guid id)
      {
         return View(_gameRepository.Get<IEnumerable<Game>>(route: $"Favoris/{id}",token: _session.ConnectedUser.Token));
      }
   }
}

DemoASP/Controllers/GenreController.cs
using DAL.Interfaces;
using DAL.Models;
using DemoASP.Tools;
using Microsoft.AspNetCore.Mvc;

namespace DemoASP.Controllers
{
   [CustomAdmin]
   public class GenreController : Controller
   {
      private readonly IGenreRepository _genreRepository;
      public GenreController(IGenreRepository genreRepository)
      {
         _genreRepository = genreRepository;
      }
      public IActionResult List()
      {
         return View(_genreRepository.Get<IEnumerable<Genre>>());
      }

      public IActionResult Add() 
      {
         return View();
      }
      [HttpPost]
      public IActionResult Add(Genre g)
      {
         if (!ModelState.IsValid) 
         {
            return View(g);
         }
         _genreRepository.Post<string>(g,route:"add");
         return RedirectToAction("List");
      }

      public IActionResult Delete(int id) 
      {
         _genreRepository.Delete(route:id.ToString());
         return RedirectToAction("List");
      }
   }
}

DemoASP/Controllers/HomeController.cs
using DemoASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoASP.Controllers
{
   public class HomeController : Controller
   {
      private readonly ILogger<HomeController> _logger;

      public HomeController(ILogger<HomeController> logger)
      {
         _logger = logger;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult Privacy()
      {

         return View();
      }
      public IActionResult NotFound() 
      {
         return View();
      }
      public IActionResult NotAuth()
      {
         return View();
      }

      [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }
   }
}

DemoASP/Controllers/UserController.cs
using DAL.Interfaces;
using DAL.Models;
using DemoASP.Models.Mappers;
using DemoASP.Models.ViewModel;
using DemoASP.Tools;
using Microsoft.AspNetCore.Mvc;

namespace DemoASP.Controllers
{
   public class UserController : Controller
   {
      private readonly IUserRepository _userRepository;
      private readonly SessionManager _session;
      public UserController(IUserRepository userRepository, SessionManager session)
      {
         _userRepository = userRepository;
         _session = session;
      }
      public IActionResult Index(Guid id)
      {

         return View(_userRepository.Get<User>(route: id.ToString(), token: _session.ConnectedUser.Token));
      }

      public IActionResult List()
      {
         return View(_userRepository.Get<IEnumerable<User>>().Select(u => u.ToUserView()));
      }

      public IActionResult Register()
      {
         return View();
      }
      [HttpPost]
      public IActionResult Register(UserRegisterForm user)
      {
         if (!ModelState.IsValid)
         {
            return View(user);
         }
         _userRepository.Post<User>(new { user.Email, user.Password, user.Username }, route: "register");

         return RedirectToAction("Index", "Home");
      }
      public IActionResult Login()
      {
         return View();
      }
      [HttpPost]
      public IActionResult Login(UserLoginForm user)
      {
         if (!ModelState.IsValid)
         {
            return View();
         }
         try
         {
            User u = _userRepository.Post<User>(new { user.Email, user.Password },route: "login");
            _session.ConnectedUser = u;
            return RedirectToAction("Index", new { id = _session.ConnectedUser.Id });
         }
         catch (Exception ex)
         {
            TempData["error"] = ex.Message;
            return View();
         }
      }

      public IActionResult Logout()
      {
         _session.Logout();
         return RedirectToAction("Index", "Home");
      }

   }
}

DemoASP/Views/Game/Create.cshtml
@using DAL.Interfaces;
@using DAL.Models;
@model DAL.Models.Game
@inject IGenreRepository GenreRepo;

@{
   ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Game</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="Create">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Genres" class="control-label"></label>
            <select asp-for="Genres.Id" class="form-select" aria-label="Choisir Genre">
               @foreach (var item in GenreRepo.Get<IEnumerable<Genre>>())
               {
                  <option value="@item.Id">@item.Label</option>
               }
            </select>
            <span asp-validation-for="Genres.Id" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Resume" class="control-label"></label>
            <input asp-for="Resume" class="form-control" />
            <span asp-validation-for="Resume" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}

DemoASP/Views/Game/Delete.cshtml
@model DAL.Models.Game

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resume)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoASP/Views/Game/Details.cshtml
@using DemoASP.Tools;
@model DAL.Models.Game
@inject SessionManager session;

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genres.Label)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resume)
        </dd>
    </dl>
</div>
<div>

    @if(session.ConnectedUser is not null)@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

DemoASP/Views/Game/Edit.cshtml
@using DAL.Interfaces;
@using DAL.Models;
@model DAL.Models.Game
@inject IGenreRepository GenreRepo;
@{
   ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Game</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="Edit">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Genres" class="control-label"></label>
            <select asp-for="Genres" class="form-select" aria-label="@Model.Genres.Label">
               @foreach (var item in GenreRepo.Get<IEnumerable<Genre>>())
               {
                  <option value="@item">@item.Label</option>
               }
            </select>
            <span asp-validation-for="Genres" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Resume" class="control-label"></label>
            <input asp-for="Resume" class="form-control" />
            <span asp-validation-for="Resume" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}

DemoASP/Views/Game/FavList.cshtml
@model IEnumerable<DAL.Models.Game>
@using DemoASP.Tools;
@inject SessionManager session;
@{
    ViewData["Title"] = "FavList";
}

<h1>Favoris</h1>

@Html.ActionLink("Back", "Index", new {  id= session.ConnectedUser.Id })

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resume)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Resume)
            </td>
@*             <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td> *@
        </tr>
}
    </tbody>
</table>

DemoASP/Views/Game/Index.cshtml
@using DemoASP.Tools;
@model IEnumerable<DAL.Models.Game>
@inject SessionManager session;

@{
   ViewData["Title"] = "Index";
}

<h1>Index</h1>

@{
   if (session.ConnectedUser is not null)
   {
      <p>
         <a asp-action="Create">Create New</a>
      </p>
      <p>
         <a asp-action="ListByGenre">Trier par genre</a>
      </p>
   }
}

<table class="table">
   <thead>
      <tr>
         <th>
            @Html.DisplayNameFor(model => model.Title)
         </th>
         <th>
            @Html.DisplayNameFor(model => model.Genres)
         </th>
         <th>
            @Html.DisplayNameFor(model => model.Resume)
         </th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      @foreach (var item in Model)
      {
         <tr>
            <td>
               @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Genres.Label)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Resume)
            </td>
            <td>
               @if (session.ConnectedUser is not null)
                  @Html.ActionLink("Edit", "Edit", new {  id=item.Id }) | 
                  @Html.ActionLink("Details", "Details", new { id=item.Id }) |
               @if (session.ConnectedUser is not null)
                  @Html.ActionLink("Delete", "Delete", new { id=item.Id })|
               @if (session.ConnectedUser is not null)
                  @Html.ActionLink("Add To favoris", "AddFavGame", new { id= item.Id })
            </td>
         </tr>
      }
   </tbody>
</table>

DemoASP/Views/Game/ListByGenre.cshtml
@using DemoASP.Tools;
@inject SessionManager session;
@model Dictionary<string,List<DAL.Models.Game>>;

@{
   ViewData["Title"] = "Par genre";
}

<h1>Par genres</h1>

@{
   if (session.ConnectedUser is not null)
   {
      <p>
         <a asp-action="Index">Go Back</a>
      </p>

   }
}

@foreach(var genre in Model)
{
   <h3>@genre.Key</h3>
   <table class="table">
      <thead>
         <tr>
            <th>
               Titre
            </th>
            <th>
               Résumé:
            </th>
         </tr>
      </thead>
      <tbody>
         @foreach (var item in genre.Value)
         {
            <tr>
               <td>
                  @Html.DisplayFor(modelItem => item.Title)
               </td>

               <td>
                  @Html.DisplayFor(modelItem => item.Resume)
               </td>
               <td>
                  @if (session.ConnectedUser is not null)
                     @Html.ActionLink("Edit", "Edit", new {  id=item.Id })

                     |
                     @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                     @if (session.ConnectedUser is not null)
                     @Html.ActionLink("Delete", "Delete", new { id=item.Id })

                  </td>
               </tr>
         }
      </tbody>
   </table>
}

DemoASP/Views/Genre/Add.cshtml
@model DAL.Models.Genre

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Label" class="control-label"></label>
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoASP/Views/Genre/List.cshtml
@model IEnumerable<DAL.Models.Genre>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Label)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Label)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new {  id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

DemoASP/Views/Home/Index.cshtml
@{
   string Name = "Pierre";
   string sName = "Pirnay";
   ViewData["Title"] = "Home Page";
}

<div class="text-center">
   <h1 class="display-4">Coucou @(Name +" "+ sName)</h1>
   <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoASP/Views/Home/NotAuth.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Vous n'avez pas les droits</h1>

DemoASP/Views/Home/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Erreur : page non trouvée</h1>

DemoASP/Views/Shared/_Layout.cshtml
@using DemoASP.Tools;
@inject SessionManager session;
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - DemoASP</title>
   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   <link rel="stylesheet" href="~/DemoASP.styles.css" asp-append-version="true" />
</head>
<body>
   <header>
      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoASP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
               <ul class="navbar-nav flex-grow-1">
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                  </li>
                  @if (session.ConnectedUser is not null && session.ConnectedUser.Role == DAL.Models.Enums.Role.Admin)
                  {
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="List">Genres</a>
                  </li>
                  }
               </ul>
               <ul class="navbar-nav">

                  @{
                     if (session.ConnectedUser is null)
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                     }
                     else
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index" asp-route-id ="@session.ConnectedUser.Id">@session.ConnectedUser.UserName - @session.ConnectedUser.Role</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                        </li>
                     }
                     if (session.ConnectedUser is not null && session.ConnectedUser.Role == DAL.Models.Enums.Role.Admin)
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">Users</a>
                        </li>
                     }
                  }
               </ul>
            </div>
         </div>
      </nav>
   </header>
   <div class="container">
      <main role="main" class="pb-3">
         @RenderBody()
      </main>
   </div>

   <footer class="border-top footer text-muted">
      <div class="container">
         &copy; 2023 - DemoASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
   </footer>
   <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   <script src="~/js/site.js" asp-append-version="true"></script>
   @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoASP/Views/User/ChangeRole.cshtml
@model DAL.Models.User

@{
   ViewData["Title"] = "ChangeRole";
}

<h1>ChangeRole</h1>

<h4>User</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="ChangeRole">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group" hidden>
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
         </div>
         <div class="form-group" hidden>
            <label asp-for="UserName" class="control-label"></label>
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
         </div>
         <div class="form-group" hidden>
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
         </div>
         <div class="form-group" hidden>
            <label asp-for="RoleId" class="control-label">Role</label>
            <input asp-for="RoleId" class="form-control" />
            <span asp-validation-for="RoleId" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="RoleId" class="control-label">Role</label>
            <select asp-for="RoleId" class="form-select" aria-label="@Model.Role">
               <option value="1">User</option>
               <option value="2">Modo</option>
               <option value="3">Admin</option>
            </select>
            <span asp-validation-for="RoleId" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}

DemoASP/Views/User/Index.cshtml
@model DAL.Models.User
@using DemoASP.Tools;
@inject SessionManager session;
@{
    ViewData["Title"] = "Index";
}

<h1>Welcome</h1>

<h4>@Model.UserName</h4>

@{
   if (session.ConnectedUser is not null)
   {
      <p><a asp-controller="Game" asp-action="FavList" asp-route-id="@session.ConnectedUser.Id">Go to your favoris games</a></p>
   }
}

DemoASP/Views/User/List.cshtml
@model IEnumerable<DemoASP.Models.ViewModel.UserView>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
               <a asp-action="ChangeRole" asp-controller="User" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Role)</a>
            </td>
@*             <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td> *@
        </tr>
}
    </tbody>
</table>